export const movies = [
  { 
    id: 1,
    title: 'The Matrix',
    category: 'Action',
    img: 'https://static1.srcdn.com/wordpress/wp-content/uploads/2025/01/poster-art-for-the-matrix-1.jpg',
    score: 10,
    trailer: 'm8e-FF8MsqU',
  },
  {
    id: 2,
    title: 'Movie 2',
    category: 'Drama',
    img: 'https://images.pexels.com/photos/1133957/pexels-photo-1133957.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 8.7,
    trailer: 'm8e-FF8MsqU',
  },
  {
    id: 3,
    title: 'Movie 3',
    category: 'Comedy',
    img: 'https://images.pexels.com/photos/247599/pexels-photo-247599.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 8.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 4,
    title: 'Movie 4',
    category: 'Thriller',
    img: 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 5,
    title: 'Movie 5',
    category: 'Horror',
    img: 'https://images.pexels.com/photos/248159/pexels-photo-248159.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 6,
    title: 'Movie 6',
    category: 'Romance',
    img: 'https://images.pexels.com/photos/36487/above-adventure-aerial-air.jpg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 7,
    title: 'Movie 7',
    category: 'Sci-Fi',
    img: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 8,
    title: 'Movie 8',
    category: 'Adventure',
    img: 'https://images.pexels.com/photos/1227513/pexels-photo-1227513.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 9,
    title: 'Movie 9',
    category: 'Mystery',
    img: 'https://images.pexels.com/photos/167684/pexels-photo-167684.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
  {
    id: 10,
    title: 'Movie 10',
    category: 'Fantasy',
    img: 'https://images.pexels.com/photos/212324/pexels-photo-212324.jpeg?auto=compress&cs=tinysrgb&w=800',
    score: 5.7,
    trailer: '1FLYZdxsteo',
  },
];